---
title: "Method of Moments with Sampling Noise"
output: html_document
---

```{r global_options, include=FALSE}
library(knitr)
library(rmarkdown)
opts_chunk$set(fig.width=12, fig.height=8, 
               echo=TRUE, warning=FALSE, message=FALSE)
```

```{r, load-libraries}

library(devtools)
library(tidyverse)
load_all()

load('../simdata/expfit-more-loci-covs.Rdata')
opar <- par(no.readonly=TRUE)

set.seed(0)

```

## Adding in Sampling Noise

We do this for only a single parameter combination, due to computational
limitations.

```{r}

add_binomial_noise <- function(x, size) {
  out <- rbinom(length(x), size, x)/size
  dim(out) <- dim(x)
  out
}


process_sampled_covs <- function(neut_freqs, as_df=TRUE, remove_fixed=TRUE,
                         standardize=TRUE, sample_size=NULL, use_conditional_variance=FALSE) {
  # this averages across loci#
  temp_cov(t(neut_freqs), as_df=as_df, swap=TRUE,
           remove_fixed=remove_fixed, standardize=standardize, 
           sample_size=sample_size, use_conditional_variance=use_conditional_variance)
}


sampled_covs <- expfit_moreloci_res %>% #filter(Va == 0.1, genlen == 0.5) %>% 
  #filter(rep %in% 1:5) %>%
  crossing(sample_size=c(50, 100, 200, 500)) %>%
  mutate(sampled_freqs =  
    map2(res, sample_size, ~ add_binomial_noise(.x$neut_freqs, size=.y))) 
  

sampled_covs <- sampled_covs  %>%
  mutate(sampled_covs = 
         map2(sampled_freqs, sample_size, 
              ~ (process_sampled_covs(.x, sample_size=.y, remove_fixed=FALSE, as_df=FALSE))))

# # no sampling noise added
# mom_fits_infinite <- expfit_moreloci_res %>% 
#     mutate(sample_size=Inf) %>%
#     mutate(mom_df = pmap(list(covs_mat, genlen, N, hets), 
#                          ~ make_neutld_df(..1, ..2, ..3, ssh=..4, 
#                                           pos=NULL,
#                                           trange=c(5, 10)))) 


# mom_fits_infinite <- mom_fits_infinite %>% mutate(lsfit = map(mom_df, fit_mom)) %>%
#                 mutate(params=map(lsfit, fit2params))


# with sampling noise
mom_fits <- sampled_covs %>% 
    mutate(mom_df = pmap(list(sampled_covs, genlen, N, hets), 
                         ~ make_neutld_df(..1, ..2, ..3, ssh=..4, 
                                          #pos=..5$pos, 
                                          pos=NULL,
                                          trange=c(5, 10))))
                                          


mom_fits <- mom_fits %>% mutate(lsfit = map(mom_df, fit_mom)) %>%
                mutate(params=map(lsfit, fit2params))


mom_fits %>% filter(Va != 0) %>% 
  mutate(emp_genic_va=map_dbl(genic_va, ~ .[5])) %>%
  mutate(emp_zvar=map_dbl(stats, ~ .$zvar[5])) %>%
  unnest(params) %>%
  ggplot(aes(emp_zvar, va0_est, color=as.factor(N))) +
  geom_point() + facet_grid(genlen~sample_size, scales='free_y') +
  geom_abline(yintercept=0, slope=1) + scale_x_log10() + scale_y_log10()


mom_fits %>% filter(Va != 0) %>% 
  mutate(emp_genic_va=map_dbl(genic_va, ~ .[5])) %>%
  mutate(emp_zvar=map_dbl(stats, ~ .$zvar[5])) %>%
  unnest(params) %>%
  ggplot(aes(emp_genic_va, va0_est)) + geom_point() + 
  geom_abline(yintercept=0, slope=1) #+ scale_x_log10() + scale_y_log10()


mom_fits %>% filter(Va != 0) %>% 
  unnest(params) %>%
  ggplot(aes(genlen, N_est, color=as.factor(sample_size))) + geom_boxplot() + 
         facet_wrap(~N) + geom_hline(aes(yintercept=N)) + ylim(0, 1e3)

```

Next, we add in the predicted Ne from the allele frequency change variation
alone.

```{r}

estimate_Ne <- function(x, t0, t1) {
  # a simple Ne estimator, Ne = t/2*F
  # where F = var(p1 - p0) / ave(het1, het0)
  x <- swap_alleles(x)
  x[x == 0 | x == 1] <- NA
  het <- x * (1-x)
  F <- var(x[t1, ] - x[t0, ], na.rm=TRUE) / mean((het[t0, ] + het[t1, ]) / 2, na.rm=TRUE)
  - (t1 - t0) / (2 * log(1-F))
}


temporal_Ne_ests <- mom_fits %>% filter(Va != 0) %>%
  mutate(Ne_est = map_dbl(res, ~ estimate_Ne(.$neut_freqs, t0=5, t1=10))) %>%
  group_by(N, Va, genlen) %>% summarize(Ne_est = mean(Ne_est, na.rm=TRUE))  %>%
  mutate(genlen=as.factor(genlen))


```

Finally we reshape the data, and save

```{r}
rec_params <- c(0.5, 0.1, 0.01, 1.5)
va_params <- c(0.01, 0.02, 0.05)

mom_fitsd_finite <- mom_fits %>% filter(N == 1e3, sample_size==100) %>% unnest(params)  %>% 
  #filter(rep %in% 1:3) %>%
  filter(Va > 0) %>%
  mutate(emp_va=map_dbl(stats, ~ .$zvar[5])) %>%
  select(rep, L:genlen, Nest=N_est, va0_est, emp_va) %>%
  filter(genlen %in% rec_params) %>%
  mutate(genlen=as.factor(as.character(genlen)))

mom_fitsd_finite <- mom_fitsd_finite %>% left_join(temporal_Ne_ests) %>%
               mutate(genlen=as.factor(genlen))

usethis::use_data(mom_fitsd_finite, overwrite=TRUE)
write_tsv(mom_fitsd_finite, '../data/mom_fits_finite.tsv')


```
## Relative error

Below we calculate the mean relative error of the parameter estimators, for
various sample sizes.

```{r}


mom_rel_error <- mom_fits %>% filter(N==1e3, L==500) %>% unnest(params) %>% 
  filter(Va > 0) %>%  mutate(emp_va=map_dbl(stats, ~ .$zvar[5])) %>%
  select(sample_size, rep, L:genlen, Nest=N_est, va0_est, emp_va) %>%
  mutate(N_error = abs((N - Nest)/N), va_error = abs((emp_va - va0_est)/emp_va)) %>%
  group_by(Va, sample_size, N,) %>% 
  summarize(N_error=median(N_error), va_error=median(va_error))  %>%
  ungroup() %>%
  mutate(Va=as.factor(Va))

usethis::use_data(mom_rel_error, overwrite=TRUE)
write_tsv(mom_rel_error, '../data/mom_rel_error.tsv')

mom_fits %>% filter(N==1e3, L==500) %>% unnest(params) %>% 
  filter(Va > 0) %>%  mutate(emp_va=map_dbl(stats, ~ .$zvar[5])) %>%
  select(sample_size, rep, L:genlen, Nest=N_est, va0_est, emp_va) %>%
  mutate(N_error = abs((N - Nest)/N), va_error = abs((emp_va - va0_est)/emp_va)) %>%
  gather(param, error, N_error, va_error)  %>%
  group_by(Va, sample_size, N, param) %>% 
  summarize(error=mean(error))  %>%
  ggplot(aes(as.factor(sample_size), error, color=as.factor(Va))) + geom_point()  + 
  facet_wrap(~param, scales='free_y')


```




